# Generated by Django 4.1 on 2022-12-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='user',
        ),
    ]
